/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'teacher' : null } |
  { 'student' : null };
export interface Doubt {
  'id' : string,
  'text' : string,
  'isAnonymous' : boolean,
  'studentSubmitter' : [] | [Principal],
  'timestamp' : Time,
  'image' : [] | [ExternalBlob],
  'isAnswered' : boolean,
  'teacherResponse' : [] | [string],
}
export interface DoubtSubmission {
  'text' : string,
  'isAnonymous' : boolean,
  'image' : [] | [ExternalBlob],
}
export type ExternalBlob = Uint8Array;
export type Time = bigint;
export interface UserProfile {
  'displayName' : string,
  'doubtsSubmitted' : bigint,
  'role' : [] | [AppRole],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'answerDoubt' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllDoubts' : ActorMethod<[], Array<Doubt>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerConfidenceScore' : ActorMethod<[], bigint>,
  'getCallerDoubts' : ActorMethod<[], Array<Doubt>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDoubt' : ActorMethod<[string], Doubt>,
  'getProfileByPrincipal' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getStudentConfidenceScore' : ActorMethod<[Principal], bigint>,
  'getTeacherNotificationCount' : ActorMethod<[], bigint>,
  'getUnansweredDoubts' : ActorMethod<[], Array<Doubt>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitDoubt' : ActorMethod<[DoubtSubmission], string>,
  'submitUserProfile' : ActorMethod<[string, AppRole], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];