/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Doubt = IDL.Record({
  'id' : IDL.Text,
  'text' : IDL.Text,
  'isAnonymous' : IDL.Bool,
  'studentSubmitter' : IDL.Opt(IDL.Principal),
  'timestamp' : Time,
  'image' : IDL.Opt(ExternalBlob),
  'isAnswered' : IDL.Bool,
  'teacherResponse' : IDL.Opt(IDL.Text),
});
export const AppRole = IDL.Variant({
  'teacher' : IDL.Null,
  'student' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'doubtsSubmitted' : IDL.Nat,
  'role' : IDL.Opt(AppRole),
});
export const DoubtSubmission = IDL.Record({
  'text' : IDL.Text,
  'isAnonymous' : IDL.Bool,
  'image' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'answerDoubt' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllDoubts' : IDL.Func([], [IDL.Vec(Doubt)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerConfidenceScore' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerDoubts' : IDL.Func([], [IDL.Vec(Doubt)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDoubt' : IDL.Func([IDL.Text], [Doubt], ['query']),
  'getProfileByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getStudentConfidenceScore' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getTeacherNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUnansweredDoubts' : IDL.Func([], [IDL.Vec(Doubt)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], ['query']),
  'submitDoubt' : IDL.Func([DoubtSubmission], [IDL.Text], []),
  'submitUserProfile' : IDL.Func([IDL.Text, AppRole], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Doubt = IDL.Record({
    'id' : IDL.Text,
    'text' : IDL.Text,
    'isAnonymous' : IDL.Bool,
    'studentSubmitter' : IDL.Opt(IDL.Principal),
    'timestamp' : Time,
    'image' : IDL.Opt(ExternalBlob),
    'isAnswered' : IDL.Bool,
    'teacherResponse' : IDL.Opt(IDL.Text),
  });
  const AppRole = IDL.Variant({ 'teacher' : IDL.Null, 'student' : IDL.Null });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'doubtsSubmitted' : IDL.Nat,
    'role' : IDL.Opt(AppRole),
  });
  const DoubtSubmission = IDL.Record({
    'text' : IDL.Text,
    'isAnonymous' : IDL.Bool,
    'image' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'answerDoubt' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllDoubts' : IDL.Func([], [IDL.Vec(Doubt)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerConfidenceScore' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerDoubts' : IDL.Func([], [IDL.Vec(Doubt)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDoubt' : IDL.Func([IDL.Text], [Doubt], ['query']),
    'getProfileByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getStudentConfidenceScore' : IDL.Func(
        [IDL.Principal],
        [IDL.Nat],
        ['query'],
      ),
    'getTeacherNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUnansweredDoubts' : IDL.Func([], [IDL.Vec(Doubt)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], ['query']),
    'submitDoubt' : IDL.Func([DoubtSubmission], [IDL.Text], []),
    'submitUserProfile' : IDL.Func([IDL.Text, AppRole], [], []),
  });
};

export const init = ({ IDL }) => { return []; };